version: '3'
services:

# Development
################################################################################
  proxy:
    build: ./development/docker-mac-network
    ports:
      - "127.0.0.1:13194:13194"
      #- "127.0.0.1:13194:13194/udp"
    command: TCP-LISTEN:13194,fork TCP:172.17.0.1:1194

  openvpn:
    image: kylemanna/openvpn
    volumes:
      - ./development/docker-mac-network:/local
      - ./development/docker-mac-network/config:/etc/openvpn
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      dest: docker-for-mac.ovpn
      DEBUG: '1'
    command: /local/helpers/run.sh

# DevOps
################################################################################

  # Postgres our Database.
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ""
    volumes:
    - ./storage/postgres:/var/lib/postgresql/data

  # Vault Secret Service
  vault:
    cap_drop:
      - IPC_LOCK
    environment:
      SKIP_SETCAP: "yes"
    image: vault
    volumes:
      - ./storage/vault/file:/vault/file
      - ./storage/vault/config:/vault/config
      - ./storage/vault/logs:/vault/logs
    command:
      - "server"

  # CD/CI
  #jenkins:
  #  image: jenkinsci/blueocean
  #  volumes:
  #    - ./storage/jenkins:/var/jenkins_home

  # Messaging
  rabbitmq:
    image: rabbitmq:management


################################################################################

  # API Gateway (TODO: Basic Image for Services.)
  gateway:
    build: ./services/gateway
    ports: ["80"]
    environment:
      VAULT_TOKEN: "13984518-9666-3c1d-1c45-e53edb8ae393"
    volumes:
      - ./services/gateway:/gateway
